BATCH_SIZE: 32
CLASSES:
- airplane
- automobile
- bird
- cat
- deer
- dog
- frog
- horse
- ship
- truck
DATASET:
  AUGMENTOR: !!python/object:lmnet.data_processor.Sequence
    processors:
    - !!python/object:lmnet.data_augmentor.FlipLeftRight
      probability: 0.5
    - !!python/object:lmnet.data_augmentor.Brightness
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.Color
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.Contrast
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.Hue
      max_value: 10
      min_value: -10
  BATCH_SIZE: 32
  DATA_FORMAT: NHWC
  PRE_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
    processors:
    - !!python/object:lmnet.pre_processor.Resize
      size:
      - 28
      - 28
    - !!python/object:lmnet.pre_processor.PerImageStandardization {}
DATASET_CLASS: !!python/name:lmnet.datasets.cifar10.Cifar10 ''
DATA_FORMAT: NHWC
IMAGE_SIZE:
- 28
- 28
IS_DEBUG: true
IS_PRETRAIN: false
KEEP_CHECKPOINT_MAX: 5
MAX_EPOCHS: 1
NETWORK:
  ACTIVATION_QUANTIZER: !!python/name:blueoil.nn.quantizations.linear.linear_mid_tread_half_quantizer ''
  ACTIVATION_QUANTIZER_KWARGS:
    bit: 2
    max_value: 2
  BATCH_SIZE: 32
  DATA_FORMAT: NHWC
  IMAGE_SIZE:
  - 28
  - 28
  OPTIMIZER_CLASS: !!python/name:tensorflow.python.training.adam.AdamOptimizer ''
  OPTIMIZER_KWARGS:
    learning_rate: 0.001
  WEIGHT_DECAY_RATE: 0.0005
  WEIGHT_QUANTIZER: !!python/name:blueoil.nn.quantizations.binary.binary_mean_scaling_quantizer ''
  WEIGHT_QUANTIZER_KWARGS: {}
NETWORK_CLASS: !!python/name:lmnet.networks.classification.lmnet_v0.LmnetV0Quantize ''
POST_PROCESSOR: null
PRETRAIN_DIR: saved/lmnet_0.01_caltech101/checkpoints
PRETRAIN_FILE: save.ckpt-99001
PRETRAIN_VARS:
- 'conv1/kernel:'
- 'conv1/bias:'
- 'conv2/kernel:'
- 'conv2/bias:'
- 'conv3/kernel:'
- 'conv3/bias:'
- 'conv4/kernel:'
- 'conv4/bias:'
- 'conv5/kernel:'
- 'conv5/bias:'
- 'conv6/kernel:'
- 'conv6/bias:'
PRE_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
  processors:
  - !!python/object:lmnet.pre_processor.Resize
    size:
    - 28
    - 28
  - !!python/object:lmnet.pre_processor.PerImageStandardization {}
SAVE_CHECKPOINT_STEPS: 100
SUMMARISE_STEPS: 10
TASK: !!python/object/apply:lmnet.common.Tasks
- IMAGE.CLASSIFICATION
TEST_STEPS: 100
