steps:
  - command: "make test-classification"
    label: "classification"
    agents:
    - "agent-type=gpu"
    - "env=production"
    timeout_in_minutes: "30"
    env:
      BUILDKITE_CLEAN_CHECKOUT: 'true'
  - command: "make test-object-detection"
    label: "object-detection"
    agents:
    - "agent-type=gpu"
    - "env=production"
    timeout_in_minutes: "40"
    env:
      BUILDKITE_CLEAN_CHECKOUT: 'true'
  - command: "make test-semantic-segmentation"
    label: "semantic-segmentation"
    agents:
    - "agent-type=gpu"
    - "env=production"
    timeout_in_minutes: "30"
    env:
      BUILDKITE_CLEAN_CHECKOUT: 'true'
  - command: "make test-keypoint-detection"
    label: "keypoint_detection"
    agents:
    - "agent-type=gpu"
    - "env=production"
    timeout_in_minutes: "30"
    env:
      BUILDKITE_CLEAN_CHECKOUT: 'true'
