steps:
  - command: "make test-unit-main"
    label: "main"
    agents:
    - "agent-type=gpu"
    - "env=production"
    timeout_in_minutes: "30"
    env:
      BUILDKITE_CLEAN_CHECKOUT: 'true'
  - command: "make test-lmnet-pep8"
    label: "pep8"
    agents:
    - "agent-type=normal"
    - "env=production"
    timeout_in_minutes: "30"
    env:
      BUILDKITE_CLEAN_CHECKOUT: 'true'
