# TCL File Generated by Component Editor 18.0
# Tue May 14 12:39:24 JST 2019
# DO NOT MODIFY


# 
# bxb "bxb" v1.0
#  2019.05.14.12:39:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bxb
# 
set_module_property DESCRIPTION ""
set_module_property NAME bxb
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bxb
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Bxb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Bxb.v VERILOG PATH Bxb.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 1
set_interface_property csr readWaitStates 0
set_interface_property csr readWaitTime 0
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr io_csrSlaveAddress address Input 6
add_interface_port csr io_csrSlaveWriteData writedata Input 32
add_interface_port csr io_csrSlaveWrite write Input 1
add_interface_port csr io_csrSlaveRead read Input 1
add_interface_port csr io_csrSlaveReadData readdata Output 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point fdma
# 
add_interface fdma avalon start
set_interface_property fdma addressUnits SYMBOLS
set_interface_property fdma associatedClock clock
set_interface_property fdma associatedReset reset
set_interface_property fdma bitsPerSymbol 8
set_interface_property fdma burstOnBurstBoundariesOnly false
set_interface_property fdma burstcountUnits WORDS
set_interface_property fdma doStreamReads false
set_interface_property fdma doStreamWrites false
set_interface_property fdma holdTime 0
set_interface_property fdma linewrapBursts false
set_interface_property fdma maximumPendingReadTransactions 0
set_interface_property fdma maximumPendingWriteTransactions 0
set_interface_property fdma readLatency 0
set_interface_property fdma readWaitTime 1
set_interface_property fdma setupTime 0
set_interface_property fdma timingUnits Cycles
set_interface_property fdma writeWaitTime 0
set_interface_property fdma ENABLED true
set_interface_property fdma EXPORT_OF ""
set_interface_property fdma PORT_NAME_MAP ""
set_interface_property fdma CMSIS_SVD_VARIABLES ""
set_interface_property fdma SVD_ADDRESS_GROUP ""

add_interface_port fdma io_fdmaAvalonAddress address Output 32
add_interface_port fdma io_fdmaAvalonBurstCount burstcount Output 10
add_interface_port fdma io_fdmaAvalonWaitRequest waitrequest Input 1
add_interface_port fdma io_fdmaAvalonWrite write Output 1
add_interface_port fdma io_fdmaAvalonWriteData writedata Output 128


# 
# connection point wdma
# 
add_interface wdma avalon start
set_interface_property wdma addressUnits SYMBOLS
set_interface_property wdma associatedClock clock
set_interface_property wdma associatedReset reset
set_interface_property wdma bitsPerSymbol 8
set_interface_property wdma burstOnBurstBoundariesOnly false
set_interface_property wdma burstcountUnits WORDS
set_interface_property wdma doStreamReads false
set_interface_property wdma doStreamWrites false
set_interface_property wdma holdTime 0
set_interface_property wdma linewrapBursts false
set_interface_property wdma maximumPendingReadTransactions 0
set_interface_property wdma maximumPendingWriteTransactions 0
set_interface_property wdma readLatency 0
set_interface_property wdma readWaitTime 1
set_interface_property wdma setupTime 0
set_interface_property wdma timingUnits Cycles
set_interface_property wdma writeWaitTime 0
set_interface_property wdma ENABLED true
set_interface_property wdma EXPORT_OF ""
set_interface_property wdma PORT_NAME_MAP ""
set_interface_property wdma CMSIS_SVD_VARIABLES ""
set_interface_property wdma SVD_ADDRESS_GROUP ""

add_interface_port wdma io_wdmaAvalon_address address Output 32
add_interface_port wdma io_wdmaAvalon_burstCount burstcount Output 10
add_interface_port wdma io_wdmaAvalon_read read Output 1
add_interface_port wdma io_wdmaAvalon_readData readdata Input 32
add_interface_port wdma io_wdmaAvalon_readDataValid readdatavalid Input 1
add_interface_port wdma io_wdmaAvalon_waitRequest waitrequest Input 1


# 
# connection point adma
# 
add_interface adma avalon start
set_interface_property adma addressUnits SYMBOLS
set_interface_property adma associatedClock clock
set_interface_property adma associatedReset reset
set_interface_property adma bitsPerSymbol 8
set_interface_property adma burstOnBurstBoundariesOnly false
set_interface_property adma burstcountUnits WORDS
set_interface_property adma doStreamReads false
set_interface_property adma doStreamWrites false
set_interface_property adma holdTime 0
set_interface_property adma linewrapBursts false
set_interface_property adma maximumPendingReadTransactions 0
set_interface_property adma maximumPendingWriteTransactions 0
set_interface_property adma readLatency 0
set_interface_property adma readWaitTime 1
set_interface_property adma setupTime 0
set_interface_property adma timingUnits Cycles
set_interface_property adma writeWaitTime 0
set_interface_property adma ENABLED true
set_interface_property adma EXPORT_OF ""
set_interface_property adma PORT_NAME_MAP ""
set_interface_property adma CMSIS_SVD_VARIABLES ""
set_interface_property adma SVD_ADDRESS_GROUP ""

add_interface_port adma io_admaAvalon_address address Output 32
add_interface_port adma io_admaAvalon_burstCount burstcount Output 10
add_interface_port adma io_admaAvalon_read read Output 1
add_interface_port adma io_admaAvalon_readData readdata Input 64
add_interface_port adma io_admaAvalon_readDataValid readdatavalid Input 1
add_interface_port adma io_admaAvalon_waitRequest waitrequest Input 1


# 
# connection point qdma
# 
add_interface qdma avalon start
set_interface_property qdma addressUnits SYMBOLS
set_interface_property qdma associatedClock clock
set_interface_property qdma associatedReset reset
set_interface_property qdma bitsPerSymbol 8
set_interface_property qdma burstOnBurstBoundariesOnly false
set_interface_property qdma burstcountUnits WORDS
set_interface_property qdma doStreamReads false
set_interface_property qdma doStreamWrites false
set_interface_property qdma holdTime 0
set_interface_property qdma linewrapBursts false
set_interface_property qdma maximumPendingReadTransactions 0
set_interface_property qdma maximumPendingWriteTransactions 0
set_interface_property qdma readLatency 0
set_interface_property qdma readWaitTime 1
set_interface_property qdma setupTime 0
set_interface_property qdma timingUnits Cycles
set_interface_property qdma writeWaitTime 0
set_interface_property qdma ENABLED true
set_interface_property qdma EXPORT_OF ""
set_interface_property qdma PORT_NAME_MAP ""
set_interface_property qdma CMSIS_SVD_VARIABLES ""
set_interface_property qdma SVD_ADDRESS_GROUP ""

add_interface_port qdma io_qdmaAvalonAddress address Output 32
add_interface_port qdma io_qdmaAvalonBurstCount burstcount Output 10
add_interface_port qdma io_qdmaAvalonRead read Output 1
add_interface_port qdma io_qdmaAvalonReadData readdata Input 64
add_interface_port qdma io_qdmaAvalonReadDataValid readdatavalid Input 1
add_interface_port qdma io_qdmaAvalonWaitRequest waitrequest Input 1


# 
# connection point rdma
# 
add_interface rdma avalon start
set_interface_property rdma addressUnits SYMBOLS
set_interface_property rdma associatedClock clock
set_interface_property rdma associatedReset reset
set_interface_property rdma bitsPerSymbol 8
set_interface_property rdma burstOnBurstBoundariesOnly false
set_interface_property rdma burstcountUnits WORDS
set_interface_property rdma doStreamReads false
set_interface_property rdma doStreamWrites false
set_interface_property rdma holdTime 0
set_interface_property rdma linewrapBursts false
set_interface_property rdma maximumPendingReadTransactions 0
set_interface_property rdma maximumPendingWriteTransactions 0
set_interface_property rdma readLatency 0
set_interface_property rdma readWaitTime 1
set_interface_property rdma setupTime 0
set_interface_property rdma timingUnits Cycles
set_interface_property rdma writeWaitTime 0
set_interface_property rdma ENABLED true
set_interface_property rdma EXPORT_OF ""
set_interface_property rdma PORT_NAME_MAP ""
set_interface_property rdma CMSIS_SVD_VARIABLES ""
set_interface_property rdma SVD_ADDRESS_GROUP ""

add_interface_port rdma io_rdmaAvalonAddress address Output 32
add_interface_port rdma io_rdmaAvalonBurstCount burstcount Output 10
add_interface_port rdma io_rdmaAvalonWaitRequest waitrequest Input 1
add_interface_port rdma io_rdmaAvalonWrite write Output 1
add_interface_port rdma io_rdmaAvalonWriteData writedata Output 64

