FROM ubuntu:16.04

MAINTAINER onogawa@leapmind.io

RUN echo "deb http://ftp.jaist.ac.jp/ubuntu/ xenial main restricted universe multiverse \n\
deb-src http://ftp.jaist.ac.jp/ubuntu/ xenial main restricted universe multiverse \n\
deb http://ftp.jaist.ac.jp/ubuntu/ xenial-updates main restricted universe multiverse \n\
deb-src http://ftp.jaist.ac.jp/ubuntu/ xenial-updates main restricted universe multiverse \n\
deb http://ftp.jaist.ac.jp/ubuntu/ xenial-backports main restricted universe multiverse \n\
deb-src http://ftp.jaist.ac.jp/ubuntu/ xenial-backports main restricted universe multiverse \n\
deb http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse \n\
deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse \n\
deb http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main \n\
deb-src http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y --allow-unauthenticated \
    build-essential \
    cmake \
    python3.6 \
    python3.6-dev \
    libjpeg8-dev \
    zlib1g-dev \
    liblapack-dev \
    libssl-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libncurses5-dev \
    libncursesw5-dev \
    locales\
    git \
    wget \
    curl \
    llvm \
    xz-utils \
    tk-dev \
    g++-5-arm-linux-gnueabihf \
    crossbuild-essential-arm64 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# x-compiler
RUN ln -s /usr/bin/arm-linux-gnueabihf-g++-5 /usr/bin/arm-linux-gnueabihf-g++

# Python
RUN ln -s /usr/bin/python3.6 /usr/bin/python 

# Install python pip
RUN curl -kL https://bootstrap.pypa.io/get-pip.py | python

# Setup lmnet
COPY lmnet /home/blueoil/lmnet
RUN touch /home/blueoil/lmnet/lmnet/__init__.py
RUN pip install -r /home/blueoil/lmnet/cpu.requirements.txt

# Build coco. It needs numpy.
# https://github.com/cocodataset/cocoapi/blob/440d145a30b410a2a6032827c568cff5dc1d2abf/PythonAPI/setup.py#L2
RUN cd /home/blueoil/lmnet/third_party/coco/PythonAPI && pip install -e .

# In order to install blueoil requirements `prompt_toolkit==1.0.15`, uninstall prompt-toolkit v2.0 that depends on `pdb==0.10.2`.
RUN pip uninstall -y prompt-toolkit

# Install dlk
COPY dlk /home/blueoil/dlk
RUN PYTHONPATH=/home/blueoil/dlk/python/dlk python /home/blueoil/dlk/setup.py install

# Install blueoil
COPY blueoil /home/blueoil/blueoil
COPY output_template /home/blueoil/output_template
COPY setup.py setup.cfg MANIFEST.in /home/blueoil/
WORKDIR /home/blueoil
RUN python setup.py install

# Enable to be written by all user
RUN chmod 777 /home/blueoil
RUN chmod 777 /home/blueoil/dlk

# Locale setting
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

ENV PYTHONPATH=/home/blueoil:/home/blueoil/lmnet:/home/blueoil/dlk/python/dlk \
    MPLBACKEND=Agg \
    DATA_DIR=/home/blueoil/dataset \
    OUTPUT_DIR=/home/blueoil/saved \
    OUTPUT_TEMPLATE_DIR=/home/blueoil/output_template
