BATCH_SIZE: 1
CLASSES:
- airplane
- automobile
- bird
- cat
- deer
- dog
- frog
- horse
- ship
- truck
DATASET:
  AUGMENTOR: !!python/object:blueoil.data_processor.Sequence
    processors:
    - !!python/object:blueoil.data_augmentor.Pad
      bottom: 2
      fill: 0
      left: 2
      right: 2
      top: 2
    - !!python/object:blueoil.data_augmentor.Crop
      height: 32
      is_resize: false
      width: 32
    - !!python/object:blueoil.data_augmentor.FlipLeftRight
      probability: 0.5
  BATCH_SIZE: 1
  DATA_FORMAT: NHWC
  PRE_PROCESSOR: !!python/object:blueoil.data_processor.Sequence
    processors:
    - !!python/object:blueoil.pre_processor.Resize
      size: !!python/tuple
      - 32
      - 32
    - !!python/object:blueoil.pre_processor.PerImageStandardization {}
DATASET_CLASS: !!python/name:blueoil.datasets.cifar10.Cifar10 ''
DATA_FORMAT: NHWC
IMAGE_SIZE:
- 32
- 32
IS_DEBUG: false
IS_PRETRAIN: false
KEEP_CHECKPOINT_MAX: 5
MAX_STEPS: 100000
NETWORK:
  BATCH_SIZE: 1
  DATA_FORMAT: NHWC
  GROUP_CONV_SIZE: 2
  IMAGE_SIZE:
  - 32
  - 32
  LEARNING_RATE_FUNC: !!python/name:tensorflow.python.training.learning_rate_decay.piecewise_constant ''
  LEARNING_RATE_KWARGS:
    boundaries:
    - 500
    - 25000
    - 50000
    - 99000
    values:
    - 0.01
    - 0.1
    - 0.01
    - 0.001
    - 0.0001
  OPTIMIZER_CLASS: !!python/name:tensorflow.python.training.momentum.MomentumOptimizer ''
  OPTIMIZER_KWARGS:
    momentum: 0.9
  WEIGHT_DECAY_RATE: 0.0005
NETWORK_CLASS: !!python/name:blueoil.networks.classification.lmnet_v1.LmnetV1GC ''
POST_PROCESSOR: null
PRETRAIN_DIR: ''
PRETRAIN_FILE: ''
PRETRAIN_VARS: []
PRE_PROCESSOR: !!python/object:blueoil.data_processor.Sequence
  processors:
  - !!python/object:blueoil.pre_processor.Resize
    size: !!python/tuple
    - 32
    - 32
  - !!python/object:blueoil.pre_processor.PerImageStandardization {}
SAVE_CHECKPOINT_STEPS: 1000
SUMMARISE_STEPS: 100
TASK: !!python/object/apply:blueoil.common.Tasks
- IMAGE.CLASSIFICATION
TEST_STEPS: 1000
