CLASSES:
- sky
- building
- pole
- road
- pavement
- tree
- signsymbol
- fence
- car
- pedestrian
- bicyclist
DATA_FORMAT: NHWC
IMAGE_SIZE:
- 360
- 480
POST_PROCESSOR: null
PRE_PROCESSOR:
- DivideBy255: null
TASK: IMAGE.SEMANTIC_SEGMENTATION
